src/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("url_checker.urls")),
]

src/url_checker/urls.py
from django.urls import path

from . import views

app_name = 'url_checker'

urlpatterns = [
    path("links/", views.link_list, name="links"),
    path("link/<int:link_id>", views.check_link, name="check_link"),
]

src/url_checker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from .choices import HTTPStatusChoice



class UserPassedLink(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user", verbose_name=_("user")
    )
    link = models.URLField(_("URL link"))
    status = models.PositiveIntegerField(_("status code"), choices=HTTPStatusChoice.choices, null=True, blank=True)
    checked_at = models.DateTimeField(_("last checked time"), auto_now=True)
    created_at = models.DateTimeField(_("created time"), auto_now_add=True)

    class Meta:
        verbose_name = _("user passed link")
        verbose_name_plural = _("user passed links")

    def __str__(self) -> str:
        return self.link

src/url_checker/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.views.decorators.http import require_GET
from django.contrib.auth.decorators import login_required

from django.utils import timezone

from .models import UserPassedLink
from .utils import url_check


@login_required(login_url="/admin/login/")
@require_GET
def link_list(request: HttpRequest) -> HttpResponse:
    queryset = UserPassedLink.objects.all()
    context = {"link_objects": queryset, "link_ids": queryset.values_list("id", flat=True)}
    return render(request, "index.html", context)


@require_GET
def check_link(request: HttpRequest, link_id: int) -> JsonResponse:
    link_obj = get_object_or_404(UserPassedLink, pk=link_id)
    response_status_code = url_check(link_obj.link)
    if link_obj.status != response_status_code:
        link_obj.status = response_status_code
        link_obj.save()
    else:
        link_obj.checked_at = timezone.now()
        link_obj.save()
    return JsonResponse({"status_code": response_status_code, "id": link_id})

src/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<button type="button">Click Me!</button>

<ul class="list-group">
    {% for link_object in link_objects %}
    {% if  link_object.status == 200 %}
    <li class="list-group-item list-group-item-success">{{ link_object.link }}  (status code: {{ link_object.status }})</li>
    {% elif link_object.status is not None %}
    <li class="list-group-item list-group-item-danger">{{ link_object.link }}   (status code: {{ link_object.status }})</li>
    {% else %}
    <li class="list-group-item">{{ link_object.link }}  (not checked)</li>
    {% endif %}
    {% endfor %}
</ul>

{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    alert("Спасибо, что обратились к нам ");
    $("button").click(function (e) {
        e.preventDefault();
            // создаем AJAX-вызов
        $.ajax({
            type: "GET",
            url: "{% url 'url_checker:check_link' link_id=1 %}",
            // если успешно, то
            success: function (response) {
            alert("Спасибо, что обратились к нам " + response.status_code);
            },
            // если ошибка, то
            error: function (response) {
                alert(response.responseJSON.errors);
                console.log(response.responseJSON.errors)
            }
        });
        return false;
    })
</script>
{% endblock javascript %}
</body>
</html>